name: NMLItems
version: '1.0'
main: io.github.NoOne.nMLItems.NMLItems
api-version: '1.21.8'
depend:
  - NMLPlayerStats
  - NMLSkills
commands:
  generateArmor:
    description: Generates a random piece of armor
    usage: /<command> <type> <rarity>
  generateShield:
    description: Generates a random shield
    usage: /<command> <level> <rarity>
  generateQuiver:
    description: Generates a random quiver
    usage: /<command> <rarity>
  generateHoe:
    description: Generates a random hoe
    usage: /<command> <rarity>